stages:
  - build
  - deploy

variables:
  # Set the public path of your Angular app
  ANGULAR_PUBLIC_PATH: "/"

install_dep:
  stage: build
  image: node:20
  script:
    - npm install -g pnpm
    - pnpm install
  cache:
    paths:
      - node_modules/
      - ~/.pnpm-store/

build_ang:
  stage: build
  image: node:20
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - ~/.pnpm-store/
    policy: pull

docker_build:
  stage: deploy
  script:
    # Build Angular project
    - ng build --prod

    # Build Docker image
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

    # Login to Docker Hub
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin

    # Push Docker image to Docker Hub
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  only:
    - master  # You can customize the branch for deployment

