image: node:20

stages:            # List of stages for jobs, and their order of execution
 - install_dependencies
 - install_angular
 - build
 

install_dep:
  stage: install_dependencies
  image: node:20
  script:
  - apt install pnpm -y
  - pnpm install

install_ang:
  stage: install_angular
  image: node:20
  script:
    - pnpm install -D typescript @angular/cli @angular/compiler

build_ang:
  stage: build
  image: node:20
  script:
  - npm run build
