stages:
  - build
  - deploy

variables:
  # Set the public path of your Angular app
  ANGULAR_PUBLIC_PATH: "/"
  # Replace with your details
  IMAGE_NAME: elwindb/thustpod
  IMAGE_TAG: latest

install_dep:
  stage: build
  image: node:20
  script:
    - npm install -g pnpm
    - pnpm install
  cache:
    paths:
      - node_modules/
      - ~/.pnpm-store/

build_ang:
  stage: build
  image: node:20
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - ~/.pnpm-store/
    policy: pull

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  # Login to DockerHub
    - docker build -t $IMAGE_NAME:$IMAGE_TAG --host unix:///var/run/docker.sock .# Build the image
    - docker push $IMAGE_NAME:$IMAGE_TAG  # Push the image to DockerHub